name: flutter_ham_tests
description: Serves HAM tests with Flutter apps.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  ff_annotation_route_library: ^3.0.0
  oktoast: ^3.3.1
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_gen: any
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
