// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************
// fast mode: true
// version: 10.0.6
// **************************************************************************
// ignore_for_file: prefer_const_literals_to_create_immutables,unused_local_variable,unused_import,unnecessary_import,unused_shown_name,implementation_imports,duplicate_import
import 'package:flutter/foundation.dart';

import 'main.dart';

const List<String> routeNames = <String>[
  'exam-page',
  'home-page',
  'questions-page',
];

class Routes {
  const Routes._();

  /// 'exam-page'
  ///
  /// [name] : 'exam-page'
  ///
  /// [constructors] :
  ///
  /// ExamPage : [Key? key, int remainsMinutes]
  static const _ExamPage examPage = _ExamPage();

  /// 'home-page'
  ///
  /// [name] : 'home-page'
  static const _HomePage homePage = _HomePage();

  /// 'questions-page'
  ///
  /// [name] : 'questions-page'
  ///
  /// [constructors] :
  ///
  /// QuestionsPage : [Key? key, String(required) title, List<Question>(required) questions]
  static const _QuestionsPage questionsPage = _QuestionsPage();
}

class _ExamPage {
  const _ExamPage();

  String get name => 'exam-page';

  Map<String, dynamic> d({
    Key? key,
    int remainsMinutes = 15,
  }) =>
      <String, dynamic>{
        'key': key,
        'remainsMinutes': remainsMinutes,
      };

  @override
  String toString() => name;
}

class _HomePage {
  const _HomePage();

  String get name => 'home-page';

  Map<String, dynamic> d({
    Key? key,
  }) =>
      <String, dynamic>{
        'key': key,
      };

  @override
  String toString() => name;
}

class _QuestionsPage {
  const _QuestionsPage();

  String get name => 'questions-page';

  Map<String, dynamic> d({
    Key? key,
    required String title,
    required List<Question> questions,
  }) =>
      <String, dynamic>{
        'key': key,
        'title': title,
        'questions': questions,
      };

  @override
  String toString() => name;
}
